<?php
return [


      //Validation messages

      'validation_no_file_selected' => 'لم يتم اختيار أي ملف.',
      'validation_image_type_invalid' => "نوع الصورة غير صالح.",
      'validation_image_too_large' => 'صورة كبيرة جداً، حجمها أكثر من 10 ميجابايت.',
      'validation_video_type_invalid' => 'نوع الفيديو غير صالح.',
      'validation_video_too_large' => 'فيديو كبير جداً، حجمه أكثر من 10 ميجابايت.',
      'validation_ip_invalid' => 'أدخل عنوان IP أو الكلمة "USB".',
      'validation_not_empty' => 'يجب ألا يكون فارغًا.',
      'validation_select_choice' => 'اختر خيارًا.',
      'validation_must_be_selected' => 'يجب تحديده.',
      'validation_numbers_only' => 'يجب أن تكون أرقامًا فقط.',
      'validation_letters_or_numbers' => 'يجب أن تكون حروفًا أو أرقامًا (بدون أحرف خاصة).',
      'validation_letters_numbers_special' => 'يجب أن تكون حروفًا، أرقامًا أو (!?\'/@.) (بدون أحرف خاصة).',
      'validation_paragraph' => 'يجب أن تكون حروفًا، أرقامًا أو (/@!?\'\';:.,) (بدون أحرف خاصة).',
      'validation_embed_link' => 'يجب أن تكون حروفًا، أرقامًا أو (://.) (بدون أحرف خاصة).',
      'validation_no_spaces' => 'يجب ألا تحتوي على مسافات.',
      'validation_invalid' => 'غير صالح.',
      'validation_no_trim_spaces' => 'يجب ألا يبدأ أو ينتهي بمسافة.',

      //Datatable Language entries

      'dT_sProcessing'    => 'جارٍ التحميل...',
      'dT_sLengthMenu'    => 'أظهر _MENU_ مدخلات',
      'dT_sZeroRecords'   => 'لم يعثر على أية سجلات',
      'dT_sInfo'          => 'إظهار _START_ إلى _END_ من أصل _TOTAL_ مدخل',
      'dT_sInfoEmpty'     => 'يعرض 0 إلى 0 من أصل 0 سجل',
      'dT_sInfoFiltered'  => '(منتقاة من مجموع _MAX_ مُدخل)',
      'dT_sSearch'        => 'ابحث:',
      'dT_searchPlaceholder' => 'بحث',
      'dT_oPaginate_sFirst'    => 'الأول',
      'dT_oPaginate_sPrevious' => 'السابق',
      'dT_oPaginate_sNext'     => 'التالي',
      'dT_oPaginate_sLast'     => 'الأخير',


      //general UI text: functions.php, global.js,..

      'place' => 'المكان',
      'order' => 'الطلبية',
      'yes' => 'نعم',
      'no' => 'لا',
      'from' => 'من',
      'page' => 'الصفحة',
      // ********** Js files messages ******************
      'oops' => "عذراً !",
      'nice' => 'جيد',
      'ok' => 'موافق',
      'comment' => "تعليق",

      //modal titles and buttons
      'modal_title_cancel' => 'إلغاء',
      'modal_title_becarefull' => "انتبه",
      'modal_title_success' => 'نجاح',
      'modal_title_empty' => 'فارغ',
      'modal_title_add_value' => 'إضافة سجل جديد',
      'modal_title_update_value' => 'تحديث السجل',
      'modal_title_update_qty' => 'تحديث الكمية',
      'modal_title_place' =>  "مكان الطلب",
      'modal_title_pay' =>  "الدفع ؟",
      'modal_title_reprint' =>  "إعادة الطباعة ؟",
      'modal_title_track_order' => 'تتبع طلبك',

      'modal_close_btn' => "إغلاق",
      'modal_check_btn' => "تحقق ...",
      'modal_reprint_btn' => "إعادة الطباعة",
      'modal_ready_btn' => "جاهز",

      'add_chef_comment' => "أضف تعليقاً للطاهي.",
      'reprint_ticket' => "إعادة طباعة التذكرة..",

      //global messages in javascript files

      //Config.php messages

      'user_error' => "عذراً! حدثت مشكلة.",
      'user_password_error' => "يرجى تحديد كلمة مرور لهذا المستخدم.",
      'user_error_cannot_delete' => "لا يمكن الحذف: ",
      'variants_already_generated' => "تم إنشاء الأنواع بالفعل.",
      'object_no_variants' => "لا يوجد أنواع لهذا العنصر للحذف.",
      'report_sales_admin_print' => "تقرير المبيعات : ",
      'report_prices_print' => "تقرير الأسعار : ",
      'licence_key_error' => "مفتاح الترخيص غير صحيح.",

      'licenceActivated' => "تم تفعيل الترخيص بنجاح.",
      'msg_choice_added' => "تمت إضافة الخيار بنجاح، التالي .. ؟",
      'msgConfirmDelSubOrder' => "هل تريد إلغاء هذا الخيار ؟",
      'msgTableValidation' => "يرجى إدخال رمز طاولة صالح.",
      'msgCarryCodeValidation' => "يرجى إدخال رمز طلب خارجي صالح.",
      'msgSuivieCommandeTable' => "يمكنك الآن تتبع تقدم طلبك في القائمة الرئيسية تحت",
      'unpaid_orders_table_warning' => "يوجد طلبيات غير مدفوعة على حساب: {tableName}\nهل تريد حقاً تأكيد هذا الطلب؟",
      'msgErrorAccured' => "حدث خطأ.",
      'msgChoixDejaAjouté' => "هذا الخيار موجود بالفعل.",
      'msgCommandeTableMenu' => "جيد. تم إضافة الطلب بنجاح.",
      'msgPlaceRequired' => "يرجى اختيار مكان للطلب.",
      'msgNameEmpty' => "الاسم لا يمكن أن يكون فارغًا.",

      'msgConfirmDeleteAttributeFromCategory' => "هل أنت متأكد أنك تريد إزالة هذه الخاصية من الفئة؟",
      'msgConfirmDelete' => "هل أنت متأكد أنك تريد حذف السجل ؟",
      'msgHaveAttribute' => "هذه الفئة لديها خاصية بالفعل.",
      'msgOperationReussie' => "تمت العملية بنجاح.",
      'msgObjectExists' => "هذا العنصر موجود بالفعل.",
      'msgObjectDelete' => "تم حذف العنصر بنجاح.",
      'msghaveMedia' => "هذه الفئة لديها وسائط بالفعل.",
      'msg_object_added' => "تمت إضافة العنصر \"{object}\" بنجاح.",
      'msg_object_updated' => "تم تحديث العنصر \"{object}\" بنجاح.",
      'msg_object_cannot_delete' => " لا يمكن حذف العنصر لأنه مستخدم في طلبية مدفوعة واحدة أو أكثر.",
      'msgmediaExists' => "هذه الوسائط موجودة بالفعل.",
      'msgLastPrice' => 'يجب التحقق من السعر الأساسي للعنصر',
      'start_after_end_warning' => "يجب أن يكون \"تاريخ البداية\" قبل \"تاريخ النهاية\".",
      'msg_cost_price_error' => "لا يمكن أن يكون سعر التكلفة أكبر من سعر البيع.",
      'msgUserLicenceLimited' => "الترخيص الخاص بك لا يسمح بعدة مستخدمين بهذا الدور.",
      'msgUserExist' => "هذا المستخدم موجود بالفعل، يرجى اختيار اسم مستخدم آخر.",
      'msgUserLicenceNotCreated' => "الترخيص غير موجود لهذه الشركة",


      //Menu page UI
      'home' => "الرئيسية",
      'food_court' => "ساحة الطعام",
      'menu' => "قائمة الطعام",
      'cart' => "تأكيد الطلبية",
      'tracking' => "متابعةالطلبية",
      'search' => "البحث",
      'notifications' => "التنبيهات",
      'login' => "الدخول",
      'logout' => "تسجيل الخروج",
      'dashboard' => "لوحة التحكم",
      'add' => "أضف",

      //***** Js text **********
      'supplements' => 'إضافة إضافات',
      'last_choice' => 'إنهاء الطلب',
      'continue' => 'إلاستمرار في الطلب',
      'main_page' => 'إلى الصفحة الرئيسية',
      'take_away_input_tooltip' => 'رمز الطلب المحمول',
      'on_table_input_tooltip' => 'رمز طاولتك',


      //********** progression modal *******/
       'order_ordered' => "تم الطلب",
      'order_validated' => "تم التأكيد",
      'order_to_chef' => "أرسل إلى الشيف",
      'order_ready' => "جاهز",
      'order_delivered' => "تم التسليم",

      // restaurent page
      'start_from' => 'ابتداءا من',

      //Product detail page
      'available' => "متوفر",
      'not_available' => "غير متوفر",
      'your_opinion' => "رأيك",

      //Cart page
      'order_validation' => "تأكيد الطلبية",
      'article'  => "الطبق",
      'price' => "السعر",
      'quantity' => "الكمية",
      'action' => "إجراء",
      'total' => "المجموع",
      'take_away' => "محمول",
      'on_table' => "على الطاولة",
      'confirm_order' => "تأكيد الطلب",

      //Login page UI
      'username' => "اسم المستخدم",
      'password' => "كلمة المرور",
      'return_home' => "إلى الصفحة الرئيسية",

      'msgUserRedirect' => "سيتم تحويلك إلى صفحة جديدة خلال ثواني.",
      'msgUserNotFound' => "لا أتعرف على اسم المستخدم هذا.",
      'msgPswNotMatch' => "اسم المستخدم وكلمة المرور غير متطابقين.",
      'msgUserStillBlocked' => "لقد وصلت إلى الحد الأقصى للمحاولات المسموح بها.\nيرجى المحاولة بعد 05 دقائق.",
      'msgUserStillConnected' => "المستخدم متصل بالفعل",

      // Cms header
      'menu' => "القائمة",
      'categories' => "الفئات",
      'articles' => "الأطباق",
      'attributes' => "الخصائص",

      'reports' => "التقارير",
      'orders' => "الطلبيات",
      'i/o' => "المبيعات/المصاريف",
      'sales_by_categories' => "المبيعات حسب الفئات",
      'earnings' => "الأرباح",

      'configuration' => "الإعدادات",
      'expense_types' => "أنواع المصاريف",
      'tables' => "الطاولات",
      'vat' => "ر.ق.م",
      'pizza_variantes' => "أنواع البيتزا",
      'printers' => "الطابعات",
      'company' => "الشركة",
      'administration' => 'الإدارة',

      //Admin Panel page
      'bouhezila_text' => 'مزود حلول تكنولوجيا المعلومات',

      'sales_day' => "مبيعات (اليوم)",
      'sales_month' => "مبيعات (الشهر)",
      'expenses_day' => "مصاريف (اليوم)",
      'expenses_month' => "مصاريف (الشهر)",
      'earnings_day' => "أرباح (اليوم)",
      'earnings_month' => "أرباح (الشهر)",
      'evolution_of_sales' => "تطور المبيعات",
      'configure_period' => "تعديل الفترة",
      'sources_of_gains' => "مصادر المبيعات",
      'top_10_articles_sold' => "أفضل 10 أطباق مباعة",
      'top_10_categories_sold' => "أفضل 10 فئات مباعة",

      //JS messages text
      'choose_last_days_title' => "اختر الأيام الأخيرة",
      'cancel_button' => "إلغاء",
      'validate_button' => "تأكيد",
      'invalid_days_warning' => "يرجى إدخال عدد أيام صحيح (> 0)",
      'choose_period_title' => "اختر الفترة",
      'start_date_label' => "تاريخ البداية:",
      'end_date_label' => "تاريخ النهاية:",
      'error_title' => "خطأ",
      'missing_dates_error' => "يرجى إدخال كلا التاريخين.",
      'invalid_date_format_error' => "تنسيق التاريخ غير صحيح (استخدم DD-MM-YYYY).",

      'top_objects_options_title' => "خيارات أفضل العناصر",
      'top_categories_options_title' => "خيارات أفضل الفئات",
      'criteria_label' => "المعيار:",
      'quantity_option' => "الكمية",
      'amount_option' => "القيمة",
      'last_days_period' => "آخر {days} يوم",
      'period_range' => "من {start} إلى {end}",
      'welcome_user' => "مرحباً السيد {familyName} {name}",


      //Category page
      'category_management_title' => 'إدارة الفئات',
      'view_categories' => 'عرض الفئات',
      'category_label' => 'الفئة',
      'prepare_label' => 'قابل للتحضير',
      'supplement_label' => 'إضافة',
      'accept_supplement_label' => 'يقبل الإضافة',
      'display_label' => 'الترتيب',
      'display_order_option' => 'ترتيب العرض',
      'color_label' => 'اللون',
      'available_label' => 'متوفر',
      'company_label' => 'الشركة',
      'date_label' => 'التاريخ',
      'action_label' => 'إجراء',
      'add_button' => 'إضافة',
      'edit_button' => 'تعديل',
      'attributes_title' => 'السمات',
      'media_uploader_title' => 'رفع الوسائط',
      'image_radio' => 'صورة',
      'video_radio' => 'فيديو',
      'upload_button' => 'رفع',
      'embed_button' => 'تضمين',

      // Articles page
      'articles_heading' => 'إدارة الأطباق',
      'alert_close' => '×',
      'loading_alt' => 'جار التحميل...',
      'table_article' => 'الطبق',
      'table_category' => 'الفئة',
      'table_available' => 'متوفر',
      'table_company' => 'الشركة',
      'table_date' => 'تاريخ',
      'table_action' => 'إجراء',
      'show_articles_btn' => 'عرض الأطباق',
      'article_label' => 'الطبق',
      'article_placeholder' => 'إسم الطبق',
      'description_label' => 'الوصف',
      'description_placeholder' => 'وصف الطبق',
      'base_price_label' => 'سعر البيع',
      'base_cost_label' => 'التكلفة الإبتدائية',
      'base_price_placeholder' => 'سعر البيع',
      'base_cost_placeholder' => 'سعر التكلفة للطبق',
      'observation_label' => 'ملاحظة',
      'observation_placeholder' => 'ملاحظة',
      'available_label' => 'متوفر',
      'add_btn' => 'إضافة',
      'edit_btn' => 'تعديل',
      'price_heading' => 'إدارة الأسعار',
      'price_alert_close' => '×',
      'attribute_select_placeholder' => 'عنصر الخاصية',
      'attribute_option_choose' => 'اختر عنصر الخاصية',
      'price_placeholder' => 'سعر بيع الخاصية',
      'cost_placeholder' => 'تكلفة الخاصية',
      'media_heading' => 'رفع الوسائط',
      'media_alert_close' => '×',
      'image_label' => 'صورة',
      'video_label' => 'فيديو',
      'upload_alt' => 'جار التحميل...',
      'upload_btn' => 'رفع',
      'media_description_placeholder' => 'الوصف',
      'show_image_div' => 'صورة',
      'show_video_div' => 'فيديو',
      'sale_price_print' => "طباعة أسعار البيع",

      //Attributes page
      'attributes_heading' => 'إدارة الخصائص',
      'section_heading' => 'الخصائص',
      'attributes_table_name' => 'اسم الخاصية',
      'attributes_table_action' => 'إجراء',
      'attributes_table_color' => 'اللون',
      'attributes_table_size' => 'الحجم',
      'values_section_heading' => 'عناصر الخاصية',
      'values_table_value' => 'العنصر',
      'values_table_action' => 'إجراء',

      //=================================================================
      //Checkout History page
      'checkout_title' => 'دفع الطلب',
      'search_placeholder' => 'الموقع، الطلب...',
      'orders_table_article' => 'الطبق',
      'orders_table_quantity' => 'الكمية',
      'orders_table_amount' => 'المبلغ',
      'orders_table_action' => 'إجراء',
      'cancel_order_btn' => 'إلغاء',
      'print_chef_btn' => 'طباعة للطاهي',
      'print_client_btn' => 'طباعة للزبون',

      //Three most used buttons in Checkout HIstory, checkout panel,
      'cancel_order_btn' => 'إلغاء',
      'print_chef_btn' => 'طباعة للطاهي',
      'print_client_btn' => 'طباعة للزبون',
      'reprint_all_btn' => 'إعادة الطباعة',

      //repoprt IO page
      'report_io_title' => 'تقرير المبيعات/المصاريف',
      'report_io_qty' => 'الكمية',
      'report_io_article' => 'الطبق',
      'report_io_amount' => 'المبلغ',
      'report_io_sales' => 'المبيعات',
      'report_io_expense' => 'المصاريف',
      'report_io_result' => 'النتيجة',
      'report_io_date' => 'التاريخ',
      'report_io_decaisse' => 'من الصندوق',
      'report_io_filter' => 'تصفية',
      'report_io_print_sales' => 'طباعة المبيعات',
      'report_io_print_expenses' => 'طباعة المصاريف',
      'report_expenses_admin_print' => 'تقرير المصاريف',
      'report_io_reset' => 'إعادة تعيين',
      'report_io_cash' => 'الصندوق',
      'report_io_total' => 'المجموع',

      // JS text
      'attribut_value_id_missed' => 'قيمة ال attribute ID مفقود.',

      // report Sales by categories page
      'sales_category_title' => 'المبيعات',
      'sales_category_cat' => 'الفئة',
      'sales_category_art' => 'الطبق',
      'sales_category_attr' => 'الخاصية',
      'sales_category_qty_total' => 'الكمية',
      'sales_category_price_total' => 'المبلغ',
      'sales_category_cost_total' => 'التكلفة',
      'sales_category_earnings_total' => 'الأرباح',
      'top_20_earnings_articles' => "أفضل  عناصر من حيث الأرباح",
      'top_20_earnings_categories' => "أفضل الفئات من حيث الأرباح",


      // JS text
      'report_select_category' => 'اختر فئة.',


      //=================================================================

      //type charge managment page

      'type_Expense_mgmt' => 'إدارة أنواع المصاريف',
      'type_expense' => 'نوع المصروف',
      'created' => 'التاريخ',
      'action' => 'إجراء',
      'view_type_expenses' => 'عرض أنواع المصاريف',
      'add_btn' => 'إضافة',
      'edit_btn' => 'تعديل',

      //table page
      'table_mgmt' => 'إدارة الطاولات',
      'table' => 'الطاولة',
      'code' => 'الرمز',
      'date' => 'التاريخ',
      'action' => 'إجراء',
      'view_tables' => 'عرض الطاولات',
      'add_btn' => 'إضافة',
      'edit_btn' => 'تعديل',

      //VAT page
      'vat_mgmt' => 'إدارة الضريبة',
      'vat' => 'الضريبة',
      'rate' => 'النسبة',

      'action' => 'إجراء',
      'view_vats' => 'عرض الضرائب',
      'add_btn' => 'إضافة',
      'edit_btn' => 'تعديل', 
      'cancel_vat' => 'إلغاء الضريبة',

      'total_ht_label'  => 'المجموع',
    'total_tva_label' => 'الضريبة',
    'total_ttc_label' => 'المجموع مع ض',

      //Pizza variants page
      'pizza_var_title' => 'إضافة أنواع البيتزا (1/2 و 1/4)',
      'pizza_var_desc' => 'تم تطوير هذا القسم لتلبية طلب خاص بالسوق الجزائري، لتوليد تلقائيًا أنواع (نصف 1/2) و(ربع 1/4) للفئات التي تبدأ بـ "Pizza". يجب أن يستوفي النظام الشروط التالية ليعمل البرنامج بشكل صحيح:',
      'pizza_var_cond1' => '1. يجب أن تبدأ الفئات الرئيسية لعناصر البيتزا بـ "Pizza" أو "PIZZA"',
      'pizza_var_ex1' => 'مثال: "Pizza Sauce Rouge"، "PIZZA Sauce Boisée"',
      'pizza_var_cond2' => '2. يجب تسمية كل عنصر ينتمي إلى فئة "Pizza" كما يلي: "Pizza + اسم العنصر"',
      'pizza_var_ex2' => 'مثال: "Pizza Margherita"، "Pizza 4 Fromages"',
      'pizza_var_cond3' => '3. يجب إنشاء عنصر بعنوان "Pizza aux choix" لاستخدام خيار الطلب المخصص',
      'pizza_var_cond4' => '4. يجب إنشاء الفئات (1/4_Pizza) و(1/2_Pizza) كإضافات',
      'pizza_var_delete_info' => 'يُستخدم زر "حذف" لإزالة العناصر التي تبدأ بـ (-1/4) أو (-1/2) من قاعدة البيانات.',
      'pizza_var_generate_1_4' => 'إضافة 1/4',
      'pizza_var_delete_1_4' => 'حذف 1/4',
      'pizza_var_generate_1_2' => 'إضافة 1/2',
      'pizza_var_delete_1_2' => 'حذف 1/2',

      //Js text
      'pizza_var_generate_success' => 'تم إنشاء أنواع البيتزا بنجاح.',
      'pizza_var_delete_success' => 'تم حذف أنواع البيتزا بنجاح.',

      //printer page
      'printer_mgmt' => 'إدارة الطابعات',
      'printer_name' => 'الاسم',
      'printer_ip' => 'IP/USB',
      'printer_port' => 'المنفذ',
      'printer_proto' => 'البروتوكول',
      'printer_labelsize' => 'حجم الملصق',
      'printer_date' => 'التاريخ',
      'printer_action' => 'إجراء',
      'printer_view' => 'عرض الطابعات',
      'printer_add' => 'إضافة',
      'printer_edit' => 'تعديل',
      'printer_categories' => 'الفئات',
      'printer_test' => 'اختبار اتصال الطابعات',

      // JS text
      'msgCheckPrinterStatus' =>  "تعذر التحقق من حالة الطابعة.",
      'msgErrorCheckPrinter' => "حدث خطأ أثناء التحقق من حالة الطابعة.",
      'modal_title_printer_status' => 'حالة الطابعة',

      // Company page (superAdminPanel)

      'company_title' => 'إدارة الشركات',
      'company_label' => 'الشركة',
      'desc_label' => 'الوصف',
      'address_label' => 'العنوان',
      'phone_label' => 'رقم الجوال',
      'email_label' => 'البريد الإلكتروني',
      'gps_label' => 'GPS',
      'take_away_label' => 'رمز الطلب الخارجي',
      'generate_btn' => 'توليد',
      'add_btn' => 'إضافة',
      'edit_btn' => 'تعديل',
      'view_companies_btn' => 'عرض الشركات',
      'media_uploader_title' => 'رفع الوسائط',
      'logo_radio' => 'شعار',
      'cover_radio' => 'غلاف',
      'upload_btn' => 'رفع',
      'options_title' => 'خيارات الشركة',
      'print_chef_label' => 'طباعة تذكرة الطباخ',
      'print_client_label' => 'طباعة إيصال العميل',
      'print_arabicRecipe_label' => "إيصال باللغة العربية",
      'order_capability_label' => 'إمكانية الطلب',
      'currency_label' => 'العملة',
      'language_label' => 'اللغة',
      'backup_base_path_label' => 'مجلد النسخ الاحتياطي الأساسي',
      'backup_base_path_ph' => 'مثال: D:\\backup',
      'browse' => 'استعراض...',
      'select_folder_title' => 'تحديد مجلد النسخ الاحتياطي',
      'current_path' => 'المسار الحالي',
      'up_one_level' => 'مستوى أعلى',
      'select_this_folder' => 'تحديد هذا المجلد',
      'admin_account_title' => 'حساب المدير',
      'username_label' => 'اسم المستخدم',
      'password_label' => 'كلمة المرور',
      'name_label' => 'الاسم',
      'family_name_label' => 'اسم العائلة',
      'admin_email_label' => 'البريد الإلكتروني',
      'delete_btn' => 'حذف',

      //Js Text
      'licence_options_updated' => "تم تحديث خيارات الترخيص بنجاح.",

      //=================================================================
      //Charge Management page
      'expense_mgmt_title' => 'إدارة المصاريف',
      'expenses_title' => 'المصاريف',
      'type_expense' => 'نوع المصروف',
      'expense_label' => 'المصروف',
      'date_label' => 'التاريخ',
      'amount_label' => 'المبلغ',
      'from_cashier_label' => 'من الصندوق',
      'obs_label' => 'ملاحظات',
      'created_label' => 'تم الإنشاء',
      'action_label' => 'إجراء',
      'view_expenses_btn' => 'عرض المصاريف',
      'observation_label' => 'ملاحظة',
      'date_placeholder' => 'التاريخ',
      'amount_placeholder' => 'المبلغ',
      'add_expense_btn' => 'إضافة مصروف',
      'edit_expense_btn' => 'تعديل المصروف',

      //Js text
      'msgExpenseAdded' => "تمت إضافة المصروف بنجاح.",
      'msgExpenseUpdated' => "تم تحديث المصروف بنجاح.",

      //user management page
      'user_mgmt' => 'إدارة المستخدمين',
      'view_users' => 'عرض المستخدمين',
      'connected' => 'متصل',
      'username' => 'اسم المستخدم',
      'password' => 'كلمة المرور',
      'name' => 'الاسم',
      'family_name' => 'اسم العائلة',
      'email' => 'البريد الإلكتروني',
      'role' => 'الدور',
      'printer' => 'الطابعة',
      'add_btn' => 'إضافة',
      'edit' => 'تعديل',
      'users_table_user' => 'المستخدم',
      'users_table_role' => 'الدور',
      'users_table_name' => 'الاسم',
      'users_table_company' => 'الشركة',
      'users_table_date' => 'التاريخ',
      'users_table_action' => 'إجراء',
      'categories' => 'الفئات',
      'alert_close' => '×',
      'loading_alt' => 'جار التحميل...',
      'select_printer' => 'الطابعات',
      'select_role' => 'الدور',

      //backup page
      'backup_title' => 'نسخ احتياطي',
      'db_backup_done' => '✅ تم نسخ قاعدة البيانات احتياطيًا بنجاح ...',
      'folder_backup_done' => '✅ تم نسخ المجلد: {folder} احتياطيًا ...',
      'folder_not_exist' => '❌ المجلد: {folder} غير موجود.',
      'menu_backup_done' => '✅ تم نسخ قائمة الطعام احتياطيًا.',
      'menu_backup_not_needed' => 'ℹ️ لا حاجة لنسخ قائمة الطعام احتياطيًا.',
      'removed_old_backup' => 'تم حذف النسخة الاحتياطية القديمة: {backup}',
      'backup_path_not_set_title' => 'مسار النسخ الاحتياطي غير محدد',
      'backup_path_not_set_msg' => 'يرجى تحديد مجلد النسخ الاحتياطي الأساسي في لوحة إعدادات الشركة قبل تشغيل النسخ الاحتياطي.',
      
      // checkoutMenu page
      'ch_menu_title' => '',
      'ch_menu_article' => 'العنصر',
      'ch_menu_qty' => 'الكمية',
      'ch_menu_price' => 'السعر',
      'ch_menu_msg' => 'إجراء',
      'ch_menu_validate_client' => 'الطاهي + الزبون',
      'ch_menu_validate' => 'إلى الطاهي',
      'ch_menu_cancel' => 'إلغاء',
      'ch_menu_alert_close' => '×',
      'ch_menu_no_orders' => 'لا توجد طلبات.',
      'ch_menu_confirm_cancel' => 'هل أنت متأكد أنك تريد إلغاء هذا الطلب؟',
      'ch_menu_success' => 'تم الدفع بنجاح.',
      'ch_menu_error' => 'حدث خطأ. يرجى المحاولة مرة أخرى.',


      //checkoutPanel and waiterPanel page
      'pay_orders'         => 'دفع الطلبات',
      'search_placeholder' => 'الموقع، الطلب..',
      'go'                 => 'انطلق!',
      'date_prefix'        => 'في ',
      'cash'               => 'الصندوق = ',
      'sales'              => 'المبيعات = ',
      'charges'            => 'المصاريف = ',
      'code'               => 'الرمز',
      'article'            => 'الطبق',
      'qty'                => 'الكمية',
      'amount'             => 'المبلغ',
      'action'             => 'الإجراء',
      'cancel'             => 'إلغاء',
      'e_ticket'           => 'إلى الطاهي',
      'pay'                => 'دفع',
      'validate'           => 'إلى الطاهي',

      //JS text
      'print_chef_text' => 'هل تريد طباعة تذكرة للطاهي؟',

];
